#pragma once

enum TipoMsg {
    LIST_FIGURES = 10,
    FIGURES_LIST = 11,

    GET_FIGURE = 14,
    RETURN_FIGURE = 15,
    FIGURE_NOT_FOUND = 104,

    INTERMEDIARY_HANDSHAKE = 150,
    INTERMEDIARY_REQUEST = 300,
    INTERMEDIARY_RESPONSE = 200,

    INVALID_FORMAT = 101,
    DESTINATION_UNAVAILABLE = 102,
    INVALID_HALF = 105,
    TIMEOUT = 106,
    UNSUPPORTED_TYPE = 107
};